fragment TeamParts on Team {
  __typename
  name
  role
  bio
  avatar
}

fragment PortfolioParts on Portfolio {
  __typename
  name
  sector
  stage
  description
  logo
  website
}

fragment PagesParts on Pages {
  __typename
  title
  heroEyebrow
  heroHeading
  heroSubtext
  heroStats {
    __typename
    stat
  }
  whyKicker
  whyHeading
  whyBody
  statCards {
    __typename
    label
    value
    description
  }
  thesisKicker
  thesisHeading
  thesisCards {
    __typename
    label
    heading
    body
  }
}
